/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


export const ErrorModel = {
  required: false,
  serializedName: 'Error',
  type: {
    name: 'Composite',
    className: 'ErrorModel',
    modelProperties: {
      status: {
        required: false,
        serializedName: 'status',
        type: {
          name: 'Number'
        }
      },
      message: {
        required: false,
        serializedName: 'message',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const A = {
  required: false,
  serializedName: 'A',
  type: {
    name: 'Composite',
    className: 'A',
    modelProperties: {
      statusCode: {
        required: false,
        serializedName: 'statusCode',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const B = {
  required: false,
  serializedName: 'B',
  type: {
    name: 'Composite',
    className: 'B',
    modelProperties: {
      statusCode: {
        required: false,
        serializedName: 'statusCode',
        type: {
          name: 'String'
        }
      },
      textStatusCode: {
        required: false,
        serializedName: 'textStatusCode',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const C = {
  required: false,
  serializedName: 'C',
  type: {
    name: 'Composite',
    className: 'C',
    modelProperties: {
      httpCode: {
        required: false,
        serializedName: 'httpCode',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const D = {
  required: false,
  serializedName: 'D',
  type: {
    name: 'Composite',
    className: 'D',
    modelProperties: {
      httpStatusCode: {
        required: false,
        serializedName: 'httpStatusCode',
        type: {
          name: 'String'
        }
      }
    }
  }
};
