/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

var internalMappers: any = {};

internalMappers.ErrorModel = {
  required: false,
  serializedName: 'Error',
  type: {
    name: 'Composite',
    className: 'ErrorModel',
    modelProperties: {
      status: {
        required: false,
        serializedName: 'status',
        type: {
          name: 'Number'
        }
      },
      message: {
        required: false,
        serializedName: 'message',
        type: {
          name: 'String'
        }
      }
    }
  }
};

internalMappers.ParameterGroupingPostRequiredParameters = {
  required: false,
  type: {
    name: 'Composite',
    className: 'ParameterGroupingPostRequiredParameters',
    modelProperties: {
      body: {
        required: true,
        type: {
          name: 'Number'
        }
      },
      customHeader: {
        required: false,
        type: {
          name: 'String'
        }
      },
      query: {
        required: false,
        defaultValue: 30,
        type: {
          name: 'Number'
        }
      },
      path: {
        required: true,
        type: {
          name: 'String'
        }
      }
    }
  }
};

internalMappers.ParameterGroupingPostOptionalParameters = {
  required: false,
  type: {
    name: 'Composite',
    className: 'ParameterGroupingPostOptionalParameters',
    modelProperties: {
      customHeader: {
        required: false,
        type: {
          name: 'String'
        }
      },
      query: {
        required: false,
        defaultValue: 30,
        type: {
          name: 'Number'
        }
      }
    }
  }
};

internalMappers.FirstParameterGroup = {
  required: false,
  type: {
    name: 'Composite',
    className: 'FirstParameterGroup',
    modelProperties: {
      headerOne: {
        required: false,
        type: {
          name: 'String'
        }
      },
      queryOne: {
        required: false,
        defaultValue: 30,
        type: {
          name: 'Number'
        }
      }
    }
  }
};

internalMappers.ParameterGroupingPostMultiParamGroupsSecondParamGroup = {
  required: false,
  type: {
    name: 'Composite',
    className: 'ParameterGroupingPostMultiParamGroupsSecondParamGroup',
    modelProperties: {
      headerTwo: {
        required: false,
        type: {
          name: 'String'
        }
      },
      queryTwo: {
        required: false,
        defaultValue: 30,
        type: {
          name: 'Number'
        }
      }
    }
  }
};

export const Mappers = internalMappers;
