/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import {CloudErrorMapper, BaseResourceMapper } from "ms-rest-azure";

export const CloudError = CloudErrorMapper;
export const BaseResource = BaseResourceMapper;

export const ErrorModel = {
  required: false,
  serializedName: 'Error',
  type: {
    name: 'Composite',
    className: 'ErrorModel',
    modelProperties: {
      status: {
        required: false,
        serializedName: 'status',
        type: {
          name: 'Number'
        }
      },
      constantId: {
        required: false,
        serializedName: 'constantId',
        type: {
          name: 'Number'
        }
      },
      message: {
        required: false,
        serializedName: 'message',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const OdataFilter = {
  required: false,
  serializedName: 'OdataFilter',
  type: {
    name: 'Composite',
    className: 'OdataFilter',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      name: {
        required: false,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const HeaderCustomNamedRequestIdParamGroupingParameters = {
  required: false,
  type: {
    name: 'Composite',
    className: 'HeaderCustomNamedRequestIdParamGroupingParameters',
    modelProperties: {
      fooClientRequestId: {
        required: true,
        type: {
          name: 'String'
        }
      }
    }
  }
};
